---
title: "JMW_tutorial"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(rjags)
library(dplyr)
library(tidyr)
library(rjags)
```

This tutorial can be found at:
http://www.johnmyleswhite.com/notebook/2010/08/20/using-jags-in-r-with-the-rjags-package/


```{r cars}

N <- 1000
x <- rnorm(N, 0, 5)

```

```{r}

# set up model object in R
jags <- jags.model('example1.bug', 
                   data = list('x' = x,   # must match names in .bug file
                               'N' = N),  # must match names in .bug file
                   n.chains = 4,          # number of parallel chains to run
                   n.adapt = 100)         # number of samples to throw away as part of adaptive sampling period for                                             each chain

update(jags, 1000) # run another 1000 iterations of the sampler - demo, unnecessary for this simple problem

jags.samples(jags,                        # draw 1000 samples from the sampler for the values of mu and tau
             c('mu', 'tau'),              # the output provides proposed values for mu and tau (precision)
             1000)                        #     will be close to 0 and 0.04 because we set them at start
                                          #     we set sd = 5. so var = 25 and precision = 1/25 = 0.04

```





